services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: eastgate-postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: eastgate
      POSTGRES_PASSWORD: eastgate
      POSTGRES_DB: eastgate_db
    ports:
      - "15454:5432"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge