/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as AuthRouteRouteImport } from './app/_auth/route'
import { Route as AuthForgotpasswordRouteImport } from './app/_auth/forgotpassword'
import { Route as AuthLogInRouteImport } from './app/_auth/logIn'
import { Route as AuthSignupRouteImport } from './app/_auth/signup'
import { Route as PbceastgateAdminRouteRouteImport } from './app/_pbceastgate/_admin/route'
import { Route as PbceastgateClientRouteRouteImport } from './app/_pbceastgate/_client/route'
import { Route as PbceastgateAdminDashboardRouteImport } from './app/_pbceastgate/_admin/dashboard'
import { Route as PbceastgateClientProtectedRouteRouteImport } from './app/_pbceastgate/_client/_protected/route'
import { Route as PbceastgateClientHomeRouteImport } from './app/_pbceastgate/_client/home'
import { Route as PbceastgateClientProtectedProfileRouteImport } from './app/_pbceastgate/_client/_protected/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotpasswordRoute = AuthForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogInRoute = AuthLogInRouteImport.update({
  id: '/logIn',
  path: '/logIn',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PbceastgateAdminRouteRoute = PbceastgateAdminRouteRouteImport.update({
  id: '/_pbceastgate/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PbceastgateClientRouteRoute = PbceastgateClientRouteRouteImport.update({
  id: '/_pbceastgate/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const PbceastgateAdminDashboardRoute =
  PbceastgateAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PbceastgateAdminRouteRoute,
  } as any)
const PbceastgateClientProtectedRouteRoute =
  PbceastgateClientProtectedRouteRouteImport.update({
    id: '/_protected',
    getParentRoute: () => PbceastgateClientRouteRoute,
  } as any)
const PbceastgateClientHomeRoute = PbceastgateClientHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PbceastgateClientRouteRoute,
} as any)
const PbceastgateClientProtectedProfileRoute =
  PbceastgateClientProtectedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => PbceastgateClientProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgotpassword': typeof AuthForgotpasswordRoute
  '/logIn': typeof AuthLogInRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof PbceastgateAdminDashboardRoute
  '/home': typeof PbceastgateClientHomeRoute
  '/profile': typeof PbceastgateClientProtectedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotpassword': typeof AuthForgotpasswordRoute
  '/logIn': typeof AuthLogInRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof PbceastgateAdminDashboardRoute
  '/home': typeof PbceastgateClientHomeRoute
  '/profile': typeof PbceastgateClientProtectedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_pbceastgate/_admin': typeof PbceastgateAdminRouteRouteWithChildren
  '/_pbceastgate/_client': typeof PbceastgateClientRouteRouteWithChildren
  '/_auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/_auth/logIn': typeof AuthLogInRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_pbceastgate/_client/_protected': typeof PbceastgateClientProtectedRouteRouteWithChildren
  '/_pbceastgate/_admin/dashboard': typeof PbceastgateAdminDashboardRoute
  '/_pbceastgate/_client/home': typeof PbceastgateClientHomeRoute
  '/_pbceastgate/_client/_protected/profile': typeof PbceastgateClientProtectedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotpassword'
    | '/logIn'
    | '/signup'
    | '/dashboard'
    | '/home'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotpassword'
    | '/logIn'
    | '/signup'
    | '/dashboard'
    | '/home'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_pbceastgate/_admin'
    | '/_pbceastgate/_client'
    | '/_auth/forgotpassword'
    | '/_auth/logIn'
    | '/_auth/signup'
    | '/_pbceastgate/_client/_protected'
    | '/_pbceastgate/_admin/dashboard'
    | '/_pbceastgate/_client/home'
    | '/_pbceastgate/_client/_protected/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PbceastgateAdminRouteRoute: typeof PbceastgateAdminRouteRouteWithChildren
  PbceastgateClientRouteRoute: typeof PbceastgateClientRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgotpassword': {
      id: '/_auth/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof AuthForgotpasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/logIn': {
      id: '/_auth/logIn'
      path: '/logIn'
      fullPath: '/logIn'
      preLoaderRoute: typeof AuthLogInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_pbceastgate/_admin': {
      id: '/_pbceastgate/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PbceastgateAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pbceastgate/_client': {
      id: '/_pbceastgate/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PbceastgateClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pbceastgate/_admin/dashboard': {
      id: '/_pbceastgate/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PbceastgateAdminDashboardRouteImport
      parentRoute: typeof PbceastgateAdminRouteRoute
    }
    '/_pbceastgate/_client/_protected': {
      id: '/_pbceastgate/_client/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PbceastgateClientProtectedRouteRouteImport
      parentRoute: typeof PbceastgateClientRouteRoute
    }
    '/_pbceastgate/_client/home': {
      id: '/_pbceastgate/_client/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PbceastgateClientHomeRouteImport
      parentRoute: typeof PbceastgateClientRouteRoute
    }
    '/_pbceastgate/_client/_protected/profile': {
      id: '/_pbceastgate/_client/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PbceastgateClientProtectedProfileRouteImport
      parentRoute: typeof PbceastgateClientProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotpasswordRoute: typeof AuthForgotpasswordRoute
  AuthLogInRoute: typeof AuthLogInRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotpasswordRoute: AuthForgotpasswordRoute,
  AuthLogInRoute: AuthLogInRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PbceastgateAdminRouteRouteChildren {
  PbceastgateAdminDashboardRoute: typeof PbceastgateAdminDashboardRoute
}

const PbceastgateAdminRouteRouteChildren: PbceastgateAdminRouteRouteChildren = {
  PbceastgateAdminDashboardRoute: PbceastgateAdminDashboardRoute,
}

const PbceastgateAdminRouteRouteWithChildren =
  PbceastgateAdminRouteRoute._addFileChildren(
    PbceastgateAdminRouteRouteChildren,
  )

interface PbceastgateClientProtectedRouteRouteChildren {
  PbceastgateClientProtectedProfileRoute: typeof PbceastgateClientProtectedProfileRoute
}

const PbceastgateClientProtectedRouteRouteChildren: PbceastgateClientProtectedRouteRouteChildren =
  {
    PbceastgateClientProtectedProfileRoute:
      PbceastgateClientProtectedProfileRoute,
  }

const PbceastgateClientProtectedRouteRouteWithChildren =
  PbceastgateClientProtectedRouteRoute._addFileChildren(
    PbceastgateClientProtectedRouteRouteChildren,
  )

interface PbceastgateClientRouteRouteChildren {
  PbceastgateClientProtectedRouteRoute: typeof PbceastgateClientProtectedRouteRouteWithChildren
  PbceastgateClientHomeRoute: typeof PbceastgateClientHomeRoute
}

const PbceastgateClientRouteRouteChildren: PbceastgateClientRouteRouteChildren =
  {
    PbceastgateClientProtectedRouteRoute:
      PbceastgateClientProtectedRouteRouteWithChildren,
    PbceastgateClientHomeRoute: PbceastgateClientHomeRoute,
  }

const PbceastgateClientRouteRouteWithChildren =
  PbceastgateClientRouteRoute._addFileChildren(
    PbceastgateClientRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PbceastgateAdminRouteRoute: PbceastgateAdminRouteRouteWithChildren,
  PbceastgateClientRouteRoute: PbceastgateClientRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
