/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as BaseRouteImport } from './app/_base'
import { Route as MerchRouteImport } from './app/_merch'
import { Route as ProtectedRouteImport } from './app/_protected'
import { Route as AuthForgotpasswordRouteImport } from './app/_auth/forgotpassword'
import { Route as AuthLogInRouteImport } from './app/_auth/logIn'
import { Route as AuthSignupRouteImport } from './app/_auth/signup'
import { Route as BaseIndexRouteImport } from './app/_base/index'
import { Route as BaseProfileRouteImport } from './app/_base/profile'
import { Route as MerchShopRouteImport } from './app/_merch/shop'
import { Route as ProtectedHomeRouteImport } from './app/_protected/home'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/_merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotpasswordRoute = AuthForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogInRoute = AuthLogInRouteImport.update({
  id: '/logIn',
  path: '/logIn',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseProfileRoute = BaseProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BaseRoute,
} as any)
const MerchShopRoute = MerchShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MerchRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/forgotpassword': typeof AuthForgotpasswordRoute
  '/logIn': typeof AuthLogInRoute
  '/signup': typeof AuthSignupRoute
  '/profile': typeof BaseProfileRoute
  '/shop': typeof MerchShopRoute
  '/home': typeof ProtectedHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseIndexRoute
  '/forgotpassword': typeof AuthForgotpasswordRoute
  '/logIn': typeof AuthLogInRoute
  '/signup': typeof AuthSignupRoute
  '/profile': typeof BaseProfileRoute
  '/shop': typeof MerchShopRoute
  '/home': typeof ProtectedHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_merch': typeof MerchRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/_auth/logIn': typeof AuthLogInRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_base/profile': typeof BaseProfileRoute
  '/_merch/shop': typeof MerchShopRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_base/': typeof BaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotpassword'
    | '/logIn'
    | '/signup'
    | '/profile'
    | '/shop'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotpassword'
    | '/logIn'
    | '/signup'
    | '/profile'
    | '/shop'
    | '/home'
  id:
    | '__root__'
    | '/_auth'
    | '/_base'
    | '/_merch'
    | '/_protected'
    | '/_auth/forgotpassword'
    | '/_auth/logIn'
    | '/_auth/signup'
    | '/_base/profile'
    | '/_merch/shop'
    | '/_protected/home'
    | '/_base/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
  MerchRoute: typeof MerchRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_merch': {
      id: '/_merch'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgotpassword': {
      id: '/_auth/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof AuthForgotpasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/logIn': {
      id: '/_auth/logIn'
      path: '/logIn'
      fullPath: '/logIn'
      preLoaderRoute: typeof AuthLogInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/profile': {
      id: '/_base/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof BaseProfileRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_merch/shop': {
      id: '/_merch/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MerchShopRouteImport
      parentRoute: typeof MerchRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotpasswordRoute: typeof AuthForgotpasswordRoute
  AuthLogInRoute: typeof AuthLogInRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotpasswordRoute: AuthForgotpasswordRoute,
  AuthLogInRoute: AuthLogInRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BaseRouteChildren {
  BaseProfileRoute: typeof BaseProfileRoute
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseProfileRoute: BaseProfileRoute,
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

interface MerchRouteChildren {
  MerchShopRoute: typeof MerchShopRoute
}

const MerchRouteChildren: MerchRouteChildren = {
  MerchShopRoute: MerchShopRoute,
}

const MerchRouteWithChildren = MerchRoute._addFileChildren(MerchRouteChildren)

interface ProtectedRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
  MerchRoute: MerchRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
