fragment UserFields on User {
  id
  firebaseUid
  name
  email
  image
  emailVerified
  banned
  banReason
  banExpires
  systemRole
  membershipStatus
  createdAt
  updatedAt
}

query CurrentUser {
  currentUser {
    ...UserFields
  }
}

query CurrentCongregant {
  currentCongregant {
    status
    user {
      ...UserFields
    }
  }
}

mutation AuthenticateCongregant {
  authenticateCongregant {
    ...UserFields
  }
}

mutation SignUpCongregant {
  signUpCongregant {
    ...UserFields
  }
}

# mutation LogoutCongregant {
#   logoutCongregant
# }
