fragment MinistryFields on Ministry {
  id
  name
  description
  headId
}

query GetMinistries {
  ministries {
    ...MinistryFields
  }
}

query GetMinistry($id: String!) {
  ministry(id: $id) {
    ...MinistryFields
  }
}

mutation CreateMinistry($input: CreateMinistryInput!) {
  createMinistry(input: $input) {
    ...MinistryFields
  }
}

mutation UpdateMinistry($id: String!, $input: UpdateMinistryInput!) {
  updateMinistry(id: $id, input: $input) {
    ...MinistryFields
  }
}

mutation DeleteMinistry($id: String!) {
  deleteMinistry(id: $id) {
    id
  }
}
